### PR TITLE
Buttons

### PR DESCRIPTION
**Pull request by farrenhi**
I might do something wrong about the pull request.

But, I closed the previous one. And, modified my trip website.

1. separators line are 1px now. Your eyes are soooooo goooood! Or, my eyes are toooooo bad?
2. radio button design is now input type as radio. previous design was just to load a picture. not really a radio design.

Thanks for reviewing the code!

Fnnn

### CODE REVIEW

**Comment by farrenhi** [comment]
Just update the code again.

Now, the attraction html would be loaded with no fee money. both radio buttons are empty as white background color.

**Comment by farrenhi** [comment]
ok many changes now...

**Review by cwpeng — CHANGES_REQUESTED** [review]
Add some paddings to your date input.

**Comment by farrenhi** [comment]
Pull request again

**Comment by farrenhi** [comment]
Pull request again

**Review by farrenhi — COMMENTED** [review]
trying to do pull request again!

**Comment by farrenhi** [comment]
@cwpeng 

not sure if this is the way to request a review...

**Comment by farrenhi** [comment]
reopen this request. @cwpeng

**Comment by farrenhi** [comment]
latest version is here.

It is from the pull request #9.

[new icon eng](https://github.com/farrenhi/taipei_trip/pull/9/commits/5994c3418330b9f651eb7a0154a7b22067f7ee76)
[5994c34](https://github.com/farrenhi/taipei_trip/pull/9/commits/5994c3418330b9f651eb7a0154a7b22067f7ee76)

**Comment by farrenhi** [comment]
> Add some paddings to your date input.

done

**Review by cwpeng — CHANGES_REQUESTED** [review]
I cannot find the website URL in this pull request. You can re-request from top right corner in this pull request page.

**Comment by farrenhi** [comment]
http://3.217.150.118:3000/attraction/12

http://3.217.150.118:3000/

Thank you!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
