### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by farrenhi**
http://3.217.150.118:3000/

Payment system is ready for further review. Thanks for helping!

Fnnn

### CODE REVIEW

**Review by cwpeng — APPROVED** [review]
OK. Done.

Your pages load /api/auth two times in page loading. It's redundant calls.

**Comment by farrenhi** [comment]
So, I just improved all the login process. Now, the traffic (reviewed via network feature on chrome or firefox) could be reviewed again. there would be only one auth.

**Comment by farrenhi** [comment]
oh and also improve the fetch/callback/promise/async-await

**Comment by farrenhi** [comment]
something is not quite right. 

the flow chart:

I saw your comment on auth twice. But, this time, I did not click merge pull request.

I modified the code and push it to github and ec2.

Did some comments and clicked re-request button...

not sure if this is correct. But, it seems that my commit comments are updated.

**Review by cwpeng — APPROVED** [review]
Looks Better.

Logically, a single pull request for a single task. But what a single task means? It depends.

**Pull request merged**
